version: '3'

services:
  ts-node:
    container_name: ts-node
    image: ts-node
    build:
      context: node
      args:
        - NODE_VERSION=${NODE_VERSION}
    environment:
      - NODE_ENV=development
      - SERVER_PORT=${SERVER_PORT}
    volumes:
      - ./..:/home/node/app
    expose:
      - "${SERVER_PORT}"
    ports:
      - "${HOST_PORT}:${SERVER_PORT}"
    command: bash -c "npm run dev"


networks:
  default:
    external:
      name: ${NETWORK}